# Generated by Django 4.2.1 on 2023-05-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='spaces/')),
                ('num_tables', models.IntegerField(default=0)),
                ('num_seats', models.IntegerField(default=0)),
                ('parking_spaces', models.BooleanField(default=False)),
            ],
        ),
    ]
