# Generated by Django 4.2.1 on 2023-05-10 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu_ms', '0003_rename_menus_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailySpecial',
        ),
    ]
